{
    'room_display_id': 55, 
    'room_real_id': 21144080, 
    'type': 'SEND_GIFT', 
    'data': 
        {
            'cmd': 'SEND_GIFT', 
            'data': 
                {
                    'action': '投喂',
                    'bag_gift': None,
                    'batch_combo_id': 'batch:gift:combo_id:12874976:392836434:31039:1700634407.0825',
                    'batch_combo_send': 
                        {
                            'action': '投喂',
                            'batch_combo_id': 'batch:gift:combo_id:12874976:392836434:31039:1700634407.0825',
                            'batch_combo_num': 1,
                            'blind_gift': None,
                            'gift_id': 31039,
                            'gift_name': '牛哇牛哇',
                            'gift_num': 1,
                            'send_master': None,
                            'uid': 12874976,
                            'uname': 'KiraKiseki'
                        },
                    'beatId': '0',
                    'biz_source': 'Live',
                    'blind_gift': None,
                    'broadcast_id': 0,
                    'coin_type': 'gold',
                    'combo_resources_id': 1,
                    'combo_send': {
                        'action': '投喂',
                        'combo_id': 'gift:combo_id:12874976:392836434:31039:1700634407.0802', 
                        'combo_num': 1,
                        'gift_id': 31039,
                        'gift_name': '牛哇牛哇', 
                        'gift_num': 1,
                        'send_master': None, 
                        'uid': 12874976, 
                        'uname': 'KiraKiseki'
                    },
                    'combo_stay_time': 5, 
                    'combo_total_coin': 100,
                    'crit_prob': 0,
                    'demarcation': 1, 
                    'discount_price': 100, 
                    'dmscore': 48, 
                    'draw': 0,
                    'effect': 0,
                    'effect_block': 0,
                    'face': 'https://i2.hdslb.com/bfs/face/29acac2dd587c7dd4ca85f93b4d080fb17cfb401.jpg', 
                    'face_effect_id': 0,
                    'face_effect_type': 0,
                    'float_sc_resource_id': 0,
                    'giftId': 31039, 
                    'giftName': '牛哇牛哇',
                    'giftType': 0,
                    'gift_tag': None,
                    'gold': 0,
                    'group_medal': None,
                    'guard_level': 0,
                    'is_first': True,
                    'is_join_receiver': False,
                    'is_naming': False,
                    'is_special_batch': 0,
                    'magnification': 1,
                    'medal_info': 
                        {
                            'anchor_roomid': 0,
                            'anchor_uname': '', 
                            'guard_level': 0,
                            'icon_id': 0,
                            'is_lighted': 0,
                            'medal_color': 9272486,
                            'medal_color_border': 12632256,
                            'medal_color_end': 12632256, 
                            'medal_color_start': 12632256,
                            'medal_level': 12,
                            'medal_name': '水溅跃',
                            'special': '',
                            'target_id': 4549624
                        },
                    'name_color': '',
                    'num': 1,
                    'original_gift_name': '',
                    'price': 100,
                    'rcost': 52876064, 
                    'receive_user_info': 
                        {
                            'uid': 392836434,
                            'uname': '哔哩哔哩王者荣耀赛事'
                        }, 
                    'remain': 0, 
                    'rnd': '4444661905180744192',
                    'send_master': None,
                    'silver': 0,
                    'super': 0,
                    'super_batch_gift_num': 1,
                    'super_gift_num': 1,
                    'svga_block': 0,
                    'switch': True,
                    'tag_image': '', 
                    'tid': '4444661905180744192', 
                    'timestamp': 1700634406, 
                    'top_list': None,
                    'total_coin': 100,
                    'uid': 12874976,
                    'uname': 'KiraKiseki',
                    'wealth_level': 8
                }
        }
}